spring:
  application:
    name: auth-service

server:
  port: 9001

jwt:
  secret: YourSuperSecretKeyForHS256ThatIsLongEnough
  expiration: 86400000 # 24 hours in milliseconds

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
