// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: TddService.proto

package tdd_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestForm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req string `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *RequestForm) Reset() {
	*x = RequestForm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TddService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForm) ProtoMessage() {}

func (x *RequestForm) ProtoReflect() protoreflect.Message {
	mi := &file_TddService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForm.ProtoReflect.Descriptor instead.
func (*RequestForm) Descriptor() ([]byte, []int) {
	return file_TddService_proto_rawDescGZIP(), []int{0}
}

func (x *RequestForm) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

type ResponseSingle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseSingle) Reset() {
	*x = ResponseSingle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TddService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseSingle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSingle) ProtoMessage() {}

func (x *ResponseSingle) ProtoReflect() protoreflect.Message {
	mi := &file_TddService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSingle.ProtoReflect.Descriptor instead.
func (*ResponseSingle) Descriptor() ([]byte, []int) {
	return file_TddService_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseSingle) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_TddService_proto protoreflect.FileDescriptor

var file_TddService_proto_rawDesc = []byte{
	0x0a, 0x10, 0x54, 0x64, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x74, 0x64, 0x64, 0x5f, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x2a, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x7b, 0x0a, 0x06, 0x54, 0x64, 0x64, 0x5f, 0x56, 0x31, 0x12, 0x38,
	0x0a, 0x04, 0x54, 0x4c, 0x56, 0x31, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x74, 0x64, 0x64, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x04, 0x54, 0x4c, 0x56, 0x32,
	0x12, 0x13, 0x2e, 0x74, 0x64, 0x64, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x46, 0x6f, 0x72, 0x6d, 0x1a, 0x16, 0x2e, 0x74, 0x64, 0x64, 0x5f, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x23, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x64, 0x64, 0x2e, 0x61, 0x70, 0x70,
	0x50, 0x01, 0x5a, 0x12, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f,
	0x74, 0x64, 0x64, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TddService_proto_rawDescOnce sync.Once
	file_TddService_proto_rawDescData = file_TddService_proto_rawDesc
)

func file_TddService_proto_rawDescGZIP() []byte {
	file_TddService_proto_rawDescOnce.Do(func() {
		file_TddService_proto_rawDescData = protoimpl.X.CompressGZIP(file_TddService_proto_rawDescData)
	})
	return file_TddService_proto_rawDescData
}

var file_TddService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_TddService_proto_goTypes = []interface{}{
	(*RequestForm)(nil),    // 0: tdd_v1.RequestForm
	(*ResponseSingle)(nil), // 1: tdd_v1.ResponseSingle
	(*emptypb.Empty)(nil),  // 2: google.protobuf.Empty
}
var file_TddService_proto_depIdxs = []int32{
	2, // 0: tdd_v1.Tdd_V1.TLV1:input_type -> google.protobuf.Empty
	0, // 1: tdd_v1.Tdd_V1.TLV2:input_type -> tdd_v1.RequestForm
	1, // 2: tdd_v1.Tdd_V1.TLV1:output_type -> tdd_v1.ResponseSingle
	1, // 3: tdd_v1.Tdd_V1.TLV2:output_type -> tdd_v1.ResponseSingle
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TddService_proto_init() }
func file_TddService_proto_init() {
	if File_TddService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TddService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TddService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseSingle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TddService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TddService_proto_goTypes,
		DependencyIndexes: file_TddService_proto_depIdxs,
		MessageInfos:      file_TddService_proto_msgTypes,
	}.Build()
	File_TddService_proto = out.File
	file_TddService_proto_rawDesc = nil
	file_TddService_proto_goTypes = nil
	file_TddService_proto_depIdxs = nil
}
