spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///root/spring-cloud-microservices-showcase/config-repo
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/